apiVersion: v1
kind: ReplicationController
metadata:
  name: mongo-server
  namespace: emontoya
spec:
  replicas: 1
  selector:
    app: mongo-server
  template:
    metadata:
      name: mongo-server
      labels:
        app: mongo-server
        namespace: <namespace>
    spec:
      containers:
      - name: mongo
        image: mongo:3.6.3-jessie
        ports:
        - name: mongo-port
          containerPort: 27017
